### ISSUE TITLE
Yogurt Errors

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/yogurt#15]
**Latest Update Open Yogurt Errors/Bugs**

- user configuration setting is not saving ERROR 
- In album the edit,delete,avatar, private button is displayed to guest user - **fixed**
- Guest can't access group own page - Error: Call to a member function getVar() on string **fixed**
- yogurt/admin/visitors, /notes/ configs : Error : TypeError: date() expects parameter 2 to be int, bool given
- can't send notes, we got the message notes sent but notes is not posted
- No Upload failed redirect message for audios

**Comment by liomj** [comment]
- Can't Delete Group
- Problem with leaving Group at group.php, in the **all groups** section in groups.php
- you can only leave group at **my groups** section, but you will see the leave group button in all groups section
- when you try to click the group : Error : TypeError: in_array() expects parameter 2 to be array, null given

**Comment by liomj** [comment]
i fix the group button issue .....delete group still not working

**Comment by mambax7** [comment]
I'll be looking at it today....

**Comment by liomj** [comment]
import sample data
Error : Unable to parse at line 18 (near " pictures: '2'").

Error: Unable to parse at line 18 (near " pictures: '2'"). in file /class/libraries/vendor/xoops/xmf/src/Yaml.php line 249

**Comment by mambax7** [comment]
Yes, I didn't yet updated this yet. Coming soon....

**Comment by mambax7** [comment]
There are also some issues with the database fields, so I'll need to take a look at that as well. 
BTW - you templates are for Bootstrap 4, right?

**Comment by liomj** [comment]
Yes bootstrap 4...the rest template  conversion to bootstrap is in progress

**Comment by mambax7** [comment]
OK, I just updated the testdata and installed fresh a fresh version, and the import worked. 
Please note that I didn't test inserts of new data, and I suspect that they will be some issues. I'll be testing it now, and if all works, we could release it as a next Alpha.
What do you think?

**Comment by liomj** [comment]
Yes that will be great. All basic function should work first

 I will commit my template change in few hours

**Comment by liomj** [comment]
i will need some time to finish up the bootstrap 4 template..got some other things to do..will commit after all is ok

**Comment by mambax7** [comment]
Not a problem, 
Can you send me a PM on XOOPS website with your email?

**Comment by liomj** [comment]
other than notes, adding new photos is also not working

**Comment by mambax7** [comment]
Yes, I saw that, but didn't have yet time to fix it.

**Comment by liomj** [comment]
During working on the bootstrap 4 templates, i notice there is a reply function in the notes templates but currently it is not working

**Comment by liomj** [comment]
issue with the friend request status after the name change
1. The friend request approval is not appearing in index.php (in friends php it is ok)
2. After we send friend request, the friend request status is not changing to Friend Request Sent or pending

**Comment by liomj** [comment]
Issue with the friendship status after the name change

1. friendship status is not changing to sent or pending after sending request
2. the friendship approval is not displaying in index.php (it is ok in friends.php)

**Comment by mambax7** [comment]
Thanks!  All these issues will have to be workout out before we release our Beta 1.
I'm currently setting up tests using www.codeception.com that will hopefully help us to run tests and make sure that all features are working. I don't have much experience with Codeception, so it will be an interesting learning experience :)

**Comment by liomj** [comment]
Open bugs

- friendship status is not changing to sent or pending after sending request in index.php (it is ok in memberlist)
- the friendship approval is not displaying in index.php (it is ok in friends.php)
- No Upload failed redirect message for audios
**- mp3 is not uploaded
- dates display as 0 in notes**

**Comment by liomj** [comment]
user configuration setting still not saving..Sometimes it saving, sometimes error

**Comment by mambax7** [comment]
Can you start adding the bugs individually, so we can better track them, and close them once fixed (and eventually reopen them, if needed)?
We'll be able to add them individually to the project as well : 
https://github.com/XoopsModules25x/yogurt/projects/2

**Comment by liomj** [comment]
ok noted Mamba

**Comment by liomj** [comment]
Please refer https://github.com/XoopsModules25x/yogurt/projects/2
