### ISSUE TITLE
Yogurt To Do/Feature Request

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/yogurt#16]
new features or modifications suggestion to existing features

- Groups original large image to uploaded and inserted to db
- need to delete video to remove it from main page
- Limit video and groups per user (like photos)
- Title and date posted/updated for video
- Title for Photos
- Need date created/updated & totalmembers for groups
- Forum For groups instead of comments
- Security Level for Groups
- Comments for audios,photos,videos
- New Blocks - Recent Video, Audios, Notes
- Yogurt Statistics
- User activity 

Anybody would like to try to implement this? :-)

**Comment by mambax7** [comment]
The Yogurt Statistics are already there, in the backend:
![image](https://user-images.githubusercontent.com/613686/79554654-5d65d700-806c-11ea-9009-d2d50dcc5c0f.png)

**Comment by mambax7** [comment]
What do you think about making the Config Categories more visible by making them red? 
![image](https://user-images.githubusercontent.com/613686/79562278-ca7f6980-8078-11ea-9ee8-1eae9b64ba79.png)

I've made the change, but don't want to commit before I hear from you...

**Comment by liomj** [comment]
I think it is too striking maybe we can make it use large font heading

**Comment by liomj** [comment]
> The Yogurt Statistics are already there, in the backend:
> ![image](https://user-images.githubusercontent.com/613686/79554654-5d65d700-806c-11ea-9009-d2d50dcc5c0f.png)
> 
> And I've been working on the "Groups original large image to uploaded and inserted to db"
> 
> Many of the other features will required major refactoring of the module. I've been thinking about it, but it's a time issue...

Yes we need to adapt the statistic for user.......im having more free time lately ..i'll try to look into some of the list and see if i can implement it....

**Comment by mambax7** [comment]
> I think it is too striking maybe we can make it use large font heading

Striking is good :) 

Reg. large font - I'm not a big fan, because it takes too much precious space on the screen. 

What, if we let the user select the color of the font for the grouping?

**Comment by liomj** [comment]
Yes that will be better

**Comment by mambax7** [comment]
Starting a work on the tutorial:
https://xoops.gitbook.io/yogurt-tutorial/

You can fork and edit here:
https://github.com/XoopsDocs/yogurt-tutorial

**Comment by liomj** [comment]
other to do features

- cancel friend request
- PM inbox alert in Navbar

**Comment by liomj** [comment]
PM inbox alert in Navbar is done in https://github.com/liomj/yogurt/commit/0032e083ccb3690f35ed2e518733b84605dbccb3

**Comment by liomj** [comment]
Please refer here https://github.com/XoopsModules25x/yogurt/projects/1
