### ISSUE TITLE
New Templates for Yogurt

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/yogurt#3]
Hi i would like to try to design new templates for Yogurt module

should i use bootstrap 3 or bootstrap 4 ?

**Comment by mambax7** [comment]
Bootstrap 4 would be better...

**Comment by mambax7** [comment]
And Thank You for your initiative to do it! This is great when people want to support Open Source!!!

**Comment by liomj** [comment]
i try my best....Yogurt is a nice module but need a lot of work to fix the current error and bugs
im currently working on the template using bootstrap4 by using the xwatch4 theme
work in progress..

![screencapture-localhost-11-modules-yogurt-tribes-php-2020-04-02-21_20_33](https://user-images.githubusercontent.com/16532279/78254895-27cbd480-7529-11ea-9b8a-69b2283b3e97.png)
![screencapture-localhost-11-modules-yogurt-notebook-php-2020-04-02-21_08_43](https://user-images.githubusercontent.com/16532279/78254913-2d291f00-7529-11ea-8077-498319763ab5.png)
![screencapture-localhost-11-modules-yogurt-album-php-2020-04-02-21_10_46 (1)](https://user-images.githubusercontent.com/16532279/78254925-30bca600-7529-11ea-8b89-75c0f3f040bb.png)
![screencapture-localhost-11-modules-yogurt-video-php-2020-04-02-21_11_03 (1)](https://user-images.githubusercontent.com/16532279/78254932-34e8c380-7529-11ea-93d3-8d3db9c5ead2.png)
![screencapture-localhost-11-modules-yogurt-friends-php-2020-04-02-21_13_27](https://user-images.githubusercontent.com/16532279/78254949-3a460e00-7529-11ea-8d4a-24449ad72a75.png)
![screencapture-localhost-11-modules-yogurt-friends-php-2020-04-02-21_11_20](https://user-images.githubusercontent.com/16532279/78254962-3fa35880-7529-11ea-8039-4c28249fcdef.png)
![screencapture-localhost-11-modules-yogurt-index-php-2020-04-02-21_06_22](https://user-images.githubusercontent.com/16532279/78254971-429e4900-7529-11ea-82ce-1dbe8fe09632.png)

**Comment by mambax7** [comment]
That's a great start!  THANK YOU!!!

**Comment by Heyula** [comment]
Good job

**Comment by liomj** [comment]
Hi mamba i made some pull request..hope you can review it
https://github.com/mambax7/yogurt/

**Comment by mambax7** [comment]
Great! Thank you! 
Just committed and will test it after I merge my recent changes as well!

**Comment by mambax7** [comment]
It looks like I've messed up something in my last commit, so let me fix that and I'll let you know once it is fixed and committed to Github

**Comment by liomj** [comment]
ok Mamba.. i'll wait for your commits before making another pull request

thank you

**Comment by mambax7** [comment]
I just uploaded some changes.  Could you please take a look at them? 
You can try to insert the test data and see if it works.  
Thank you!

**Comment by liomj** [comment]
i got this error in main page
Error : Error: Class 'XoopsModules\Yogurt\FriendshipHandler' not found

user and friend avatar is missing - aren't xoops core default avatar is blank.gif and not png ?

**Comment by liomj** [comment]
tribes image missing

**Comment by liomj** [comment]
Not working
- making photo to private 
- edit photo description
- edit video description
- feature video in index page

**Comment by mambax7** [comment]
Front-end or backend?

**Comment by mambax7** [comment]
BTW - could you have a fresh installation to test it?

**Comment by mambax7** [comment]
It seems that my attempt to clean up the folders for images, i.e. to place: 
- photos in /yogurt/photos folder, and 
- tribe logos in /yogurt/tribes/, and 
- avatars in /yogurt/avatars 

backfired, because I missed several places where they point to just /uploads, as Yogurt originally was dumping all images in one place: the /uploads folder. 

OK, I'll look into it and fix it. 

Thanks for reporting it, and thanks for your patience while I'm fixing it...

**Comment by liomj** [comment]
Thank you and Take your time Mamba...

**Comment by mambax7** [comment]
Is the "Error: Class 'XoopsModules\Yogurt\FriendshipHandler' not found" still there? 

Right now these are already fixed and uploaded:

- make photo as avatar
- missing tribe logos in Profile

working on other bugs...

**Comment by liomj** [comment]
the friendshiphandler error is gone 

regarding the avatar i think there is no need for yogurt to have it own avatar own folder

since the xoops core have it own folder uploads/avatar

so yogurt avatar should be in the folder if not we will have missing avatar in the core or profile module profile

**Comment by mambax7** [comment]
You're right about the avatar - I'll change it back

**Comment by liomj** [comment]
blank avatar is missing in friendship request and friends block (noavatar,gif)

**Comment by mambax7** [comment]
blank avatar is missing in friendship request and friends block (noavatar,gif) is fixed:
https://github.com/mambax7/yogurt/commit/133e37d14d21920bec9bb9156a26858bb65a12b9

**Comment by mambax7** [comment]
https://github.com/mambax7/yogurt/commit/832b6aa088839b74fe2a068bdcd8f654200fd72f
fixed:

- making photo to private
- feature video in index page

**Comment by liomj** [comment]
edit & feat video still not working.. fresh installation

**Comment by mambax7** [comment]
Oops! Sorry, I've missed to upload the VideoHandler class:
https://github.com/mambax7/yogurt/commit/b6c72010fad9c6fd85577fa769c587ff6107fff4

**Comment by liomj** [comment]
Noted...i made some pull request..hope you can check it

**Comment by mambax7** [comment]
Done!

**Comment by liomj** [comment]
i'll close this issue and open new topics for yogurt bugs

**Comment by liomj** [comment]
https://github.com/XoopsModules25x/yogurt/commit/7b3c33efccc01731bf312f3f12448ee0c0540216
