### ISSUE TITLE
No Upload failed redirect message for audios

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/yogurt#33]
for audios

**Comment by mambax7** [comment]
What it supposed to do? 
Right now it displays an error for the user:
![image](https://user-images.githubusercontent.com/613686/80472453-bce8a000-8912-11ea-9522-23bb3d8e68bc.png)

**Comment by liomj** [comment]
> What it supposed to do? 
> Right now it displays an error for the user:
> ![image](https://user-images.githubusercontent.com/613686/80472453-bce8a000-8912-11ea-9522-23bb3d8e68bc.png)
> 
Last time when uploading a large mp3 file no failed message display

So this has been fixed

**Comment by mambax7** [comment]
This was a message after I've renamed the upload directory. 
Let me check what happens when the file is too big.

**Comment by mambax7** [comment]
It was the same error.  In the future, we will try to provide more detailed errors, e.g. 
- the file was too big
- the upload folder doesn't exist, etc.
