### ISSUE TITLE
Rename audio and video

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/yogurt#63]
Need to rename audio to audios and video to videos

so in future we can have single page for each audio and video just like the groups where each group have its own page

**Comment by mambax7** [comment]
The whole module needs a major refactoring. Right now let's just make it work as it is, and then we can start on release 4.0

**Comment by liomj** [comment]
I think this renaming is doable right now just to make it standard

**Comment by mambax7** [comment]
Let me look into it....

**Comment by mambax7** [comment]
https://github.com/XoopsModules25x/yogurt/pull/81
