### ISSUE TITLE
editpicture.php - Out of range value for column 'date_created' at row 1

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/yogurt#77]
0.000790 - UPDATE yogurt_images SET cod_img=3, title='1', caption='2', date_created=date_add(now(), interval 8 hour), date_updated=date_add(now(), interval 8 hour), uid_owner='1', url='pic_1_5ea44c116d7e2.jpg', private='0' WHERE cod_img = 3
Error number: 1264
Error message: Out of range value for column 'date_created' at row 1

**Comment by mambax7** [comment]
There are few issues with your recent code: we might use "now()" date_created for a new image, but when we update the title/caption, we don't want to touch it, we only change the "date_updated"
I'll look into it...

**Comment by mambax7** [comment]
Fixed: https://github.com/XoopsModules25x/yogurt/pull/79/commits/3001c735fa38eccbbd5d0b43d8aae6f15c95eb69
