### ISSUE TITLE
updating language for yogurt

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/yogurt#8]
some suggestion to update some terms in yogurt to be more general and specific

sexy -- > Awesome/Love ?
tribes --> Groups ?
Havent met accepted (in editfriendship section) 
Make this video your main video - Feature this video in your profile page
This Video is selected on your front page from now on - change selected to featured

**Comment by mambax7** [comment]
makes sense

**Comment by liomj** [comment]
Trusty - awesome
Sexy - lovely

:-)

**Comment by mambax7** [comment]
It's done: 
Trusty - funny
Sexy - friendly

Also renamed Tribe to Group

**Comment by liomj** [comment]
i made changes for the video part

**Comment by mambax7** [comment]
What has changed?

**Comment by liomj** [comment]
added+ and modified*

*define('_MD_YOGURT_SETMAINVIDEO', 'This video is featured on your profile page from now on');
*define(
    '_MD_YOGURT_ADDVIDEOSHELP',
    'If you want to upload your own video for sharing, upload your videos to
<a href=https://www.youtube.com>YouTube</a> and then add the URL here in'); //The name of the site will show after this
*define('_MD_YOGURT_MAKEMAIN', 'Feature this video in your main page');
*define('_MD_YOGURT_SELECTMAINVIDEO', 'Then you can select a video to feature in your profile page');
*define('_MD_YOGURT_NOMAINVIDEOYET', 'No featured video yet');
+define('_MD_YOGURT_ADDASAFRIEND', 'Add as a Friend');
+define('_MD_YOGURT_PROFILEVISITORS', 'Profile Visitors');
+define('_MD_YOGURT_FEATUREDVIDEO', 'Featured Video');
+define('_MD_YOGURT_ALLVIDEOS', 'View all videos');
