### ISSUE TITLE
Main userpage for XOOPS

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/yogurt#82]
right now if we would like yogurt to be the main userpage, user have to edit userinfo. can we remove this step ? WE should avoid user have to make changes to core files

just like the profile module, when installed it automatically replace the main userpage 

> Hack to make the yogurt userpage as the main userpage of your site:
> 
> Open ROOT_URL/userinfo.php in the root of your site, search at the very beggining of the file  for
> 
> $uid = intval($_GET['uid']);
> if ($uid <= 0) {
>     redirect_header('index.php', 3, _US_SELECTNG);
>     exit();
> }
> 
> Add after this the following lines:
> 
> header("Location:".XOOPS_URL."/modules/yogurt/index.php?uid=".$uid);
> exit();
> 
> If you are using the profile module
> 
> Open ROOT_URL/modules/profile/userinfo.php, search at the very beggining of the file  for
> 
> $uid = isset($_GET['uid']) ? (int)$_GET['uid'] : 0;
> if ($uid <= 0) {
>     if (is_object($GLOBALS['xoopsUser'])) {
>         $uid = $GLOBALS['xoopsUser']->getVar('uid');
>     } else {
>         header('location: ' . XOOPS_URL);
>         exit();
>     }
> }
> 
> Add after this the following lines:
> 
> header("Location:".XOOPS_URL."/modules/yogurt/index.php?uid=".$uid);
> exit();

**Comment by mambax7** [comment]
We don't want to hack the Core, as it will introduce an extra commitment for us.
I don't know if this will address your idea, but take a look at [eProfile](https://github.com/mambax7/eprofile). Alfred tried to use Yogurt to extend the regular Profile. I just tried to update it to make it compatible with PHP 7. Take a look and see if there is maybe a code that you could utilize, without  touching the Core.

**Comment by liomj** [comment]
Awesome, we can use eprofile module as example how to add custom field in yogurt in future release :-)

Yes we need to remove the current step to hack userinfo.php for yogurt the main userpage

Im trying to figure out in profile and eprofile module which code that makes them the default userpage when installing the modules.

**Comment by liomj** [comment]
i found it is in profile/preloads/core.php..we should implement this in yogurt

```

class ProfileCorePreload extends XoopsPreloadItem
{
    /**
     * @param $args
     */
    public static function eventCoreUserStart($args)
    {
        $op = 'main';
        if (isset($_POST['op'])) {
            $op = trim($_POST['op']);
        } elseif (isset($_GET['op'])) {
            $op = trim($_GET['op']);
        }
        if ($op !== 'login' && (empty($_GET['from']) || 'profile' !== $_GET['from'])) {
            header('location: ./modules/profile/user.php' . (empty($_SERVER['QUERY_STRING']) ? '' : '?' . $_SERVER['QUERY_STRING']));
            exit();
        }
    }

    /**
     * @param $args
     */
    public static function eventCoreEdituserStart($args)
    {
        header('location: ./modules/profile/edituser.php' . (empty($_SERVER['QUERY_STRING']) ? '' : '?' . $_SERVER['QUERY_STRING']));
        exit();
    }

    /**
     * @param $args
     */
    public static function eventCoreLostpassStart($args)
    {
        $email = isset($_GET['email']) ? trim($_GET['email']) : '';
        $email = isset($_POST['email']) ? trim($_POST['email']) : $email;
        header("location: ./modules/profile/lostpass.php?email={$email}" . (empty($_GET['code']) ? '' : '&' . $_GET['code']));
        exit();
    }

    /**
     * @param $args
     */
    public static function eventCoreRegisterStart($args)
    {
        header('location: ./modules/profile/register.php' . (empty($_SERVER['QUERY_STRING']) ? '' : '?' . $_SERVER['QUERY_STRING']));
        exit();
    }

    /**
     * @param $args
     */
    public static function eventCoreUserinfoStart($args)
    {
        header('location: ./modules/profile/userinfo.php' . (empty($_SERVER['QUERY_STRING']) ? '' : '?' . $_SERVER['QUERY_STRING']));
        exit();
    }
}
```

**Comment by mambax7** [comment]
You can also look at [SmartProfile](https://github.com/XoopsModulesArchive/smartprofile) to see if there is anything interesting for us for future versions of  Yogurt
