### ISSUE TITLE
yogurt errors 

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/yogurt#9]
from mjoel in[ xoops.org forum](https://xoops.org/modules/newbb/viewtopic.php?post_id=365024#365024)

- user configuration setting is still not saving ERROR: Configuration has not been saved
- Image for tribe is not working - only filename for gif thumb is inserted to database but not name of original image
- search a tribe is not working properly only number of search tribes is displaying
- tribe name and tribe description should be a required field
- missing tribe management link in template for tribes owner - kickfromtribe, edittribe etc
- In album the edit,delete,avatar, private button is displayed to guest user
- Image description file for photo is editdesc.php should be change to eg editdescphoto.php
- In user evaluation - editfriendship.php "Havent Met Accepted"
- in friend blocks - missing no friend yet text if no friends
- uploading mp3 in audios not working - flash audio player is not working and blocked by browser ,suggest to use jquery bootstrap mp3 player
- outdated ym,icq, aim,msn in yogurt
- friends appears twice in friend list ....

**Comment by liomj** [comment]
- join tribe button is display to current member of tribe

**Comment by mambax7** [comment]
> Image for tribe is not working
Try with jpg and png - it works fine over here. But I didn't test it with gif

**Comment by liomj** [comment]
Yes tribe for image is working...But For design wise..i think..a large image for tribe need to be uploaded and inserted to db..the large image is to be display in the tribe own page while the thumb tribe image to be display in blocks and tribe section.

**Comment by mambax7** [comment]
OK, we'll add thumbs, the same as in photos

**Comment by liomj** [comment]
error after last commit Notice: Undefined index: enable_groups in file /modules/yogurt/xoops_version.php line 573

**Comment by liomj** [comment]
Guest can't access group own page - Error: Call to a member function getVar() on string

**Comment by liomj** [comment]
**--fixed--**
search a tribe is not working properly only number of search tribes is displaying
tribe name and tribe description should be a required field
missing tribe management link in template for tribes owner - kickfromtribe, edittribe etc
Image description file for photo is editdesc.php should be change to eg editdescphoto.php
In user evaluation - editfriendship.php "Havent Met Accepted"
-- 

**-still open--**
user configuration setting is still not saving ERROR: Configuration has not been saved
In album the edit,delete,avatar, private button is displayed to guest user
Image for tribe is not working - only filename for gif thumb is inserted to database but not name of original image
in friend blocks - missing no friend yet text if no friends
uploading mp3 in audios not working - flash audio player is not working and blocked by browser ,suggest to use jquery bootstrap mp3 player
outdated ym,icq, aim,msn in yogurt
friends appears twice in friend list ....
Guest can't access group own page - Error: Call to a member function getVar() on string
join tribe button is display to current member of tribe
need to delete video to remove it from main page
potential of sql injection attack in some of files in the the class folder
Guest can't access group own page - Error: Call to a member function getVar() on string

**Comment by mambax7** [comment]
> Image for tribe is not working - only filename for gif thumb is inserted to database but not name of original image

Try with png or jpg image. For security reasons we don't use original names - the uploader should rename the uploaded images

**Comment by mambax7** [comment]
> user configuration setting is still not saving ERROR: Configuration has not been saved

I can't reproduce it here, it's working fine here. I'll have to take a look into it.

**Comment by mambax7** [comment]
BTW - this week I took a break from Yogurt to focus on other things :) 
I'll look into the other issues this weekend or next week...

**Comment by liomj** [comment]
> > user configuration setting is still not saving ERROR: Configuration has not been saved
> 
> I can't reproduce it here, it's working fine here. I'll have to take a look into it.

yes im still having it....you can also try clicking the submit button without changing anything

**Comment by liomj** [comment]
> > Image for tribe is not working - only filename for gif thumb is inserted to database but not name of original image
> 
> Try with png or jpg image. For security reasons we don't use original names - the uploader should rename the uploaded images

image tribe is working..what is meant here the large image is not uploaded and inserted to db

**Comment by liomj** [comment]
> BTW - this week I took a break from Yogurt to focus on other things :)
> I'll look into the other issues this weekend or next week...

Alright Mamba, Thank You. When you have the time, take a look and review of my pull request. i've fixed some issues

**Comment by mambax7** [comment]
I'm sorry - I didn't see your Pull Requests. I just committed them, and I'll look at them later. 
Thank you so much!!!

**Comment by liomj** [comment]
Thank you Mamba, just check now and then of my pull request will make further changes and fixes

**Comment by liomj** [comment]
Mamba can you review and approve my yogurt pull request ...Thank You

**Comment by mambax7** [comment]
There are conflicts. Could you fix them so I could merge it? 
![image](https://user-images.githubusercontent.com/613686/79119488-7a459600-7d5e-11ea-8974-9d608e21cc78.png)

**Comment by liomj** [comment]
can you try again Mamba....tq

**Comment by liomj** [comment]
check out my pull request later..i will be making some fix today for yogurt..Thank you Mamba

**Comment by liomj** [comment]
Group has a new error when uploading group image :: You can only upload jpg's files and up to 117.1875 KBytes in size

**Comment by mambax7** [comment]
Your changes or mine? 
I thought, you can change the max. size of photo upload in preferences?

**Comment by liomj** [comment]
errors when uploading some photos
--
Error: TypeError: imagecreatetruecolor() expects parameter 2 to be int, float given in file /modules/yogurt/class/ImageHandler.php line 494

**Comment by liomj** [comment]
> Your changes or mine?
> I thought, you can change the max. size of photo upload in preferences?

the default setting in pref is 500kb..havent change anything

**Comment by liomj** [comment]
can't delete videos
Notice: Undefined index: confirm in file /modules/yogurt/delvideo.php line 32

**Comment by mambax7** [comment]
OK, I'll look into it later tonight..

**Comment by liomj** [comment]
Thank you..

1. image edit, delete, set to private is not working
2. import sample data is not working

clicking the confirm button but nothing happens

**Comment by liomj** [comment]
**Latest Open Yogurt Errors/Bugs**

a. error when uploading group image :: You can only upload jpg's files and up to 117.1875 KBytes in size
b. can't delete videos
c. errors when uploading some photos
Error: TypeError: imagecreatetruecolor() expects parameter 2 to be int, float given in file /modules/yogurt/class/ImageHandler.php line 494
d. image edit, delete, set to private is not working
e. import sample data is not working
f. user configuration setting is not saving ERROR: Configuration has not been saved
g. In album the edit,delete,avatar, private button is displayed to guest user
h. Groups original large image is not uploaded and inserted to db
i. uploading mp3 in audios not working 
j. friends appearing twice in friend list ....
k. Guest can't access group own page - Error: Call to a member function getVar() on string
l. join Group button is display to current member of tribe
m. need to delete video to remove it from main page

**Comment by mambax7** [comment]
Thanks! I'll be working on now...

**Comment by mambax7** [comment]
First batch of bug fixes is uploaded. The issues were mainly related to a switch to strict type checking with "===" instead of just "=="
I'll be working now on the remaining bugs...

**Comment by liomj** [comment]
Thank you Mamba..

please review my  pull request ..

**Comment by liomj** [comment]
> First batch of bug fixes is uploaded. The issues were mainly related to a switch to strict type checking with "===" instead of just "=="
> I'll be working now on the remaining bugs...

set photos to avatar not yet working..

**Comment by liomj** [comment]
**Latest Update Open Yogurt Errors/Bugs**

- user configuration setting is not saving ERROR: Configuration has not been saved
- image set as avatar is not working
- In album the edit,delete,avatar, private button is displayed to guest user

- Groups original large image is not uploaded and inserted to db
- Guest can't access group own page - Error: Call to a member function getVar() on string
- join Group button is display to current member of GROUP

- uploading mp3 in audios not working
- need to delete video to remove it from main page
-. yogurt/admin/visitors: Error : TypeError: date() expects parameter 2 to be int, bool given

**Comment by liomj** [comment]
- Group error : you can create a group in other user group page

**Comment by liomj** [comment]
- Need to limit video and groups per user (like photos)
- Guest is redirected to admin uid=1 (should be redirect to a differenct landing page for non guest)
- Need title and date posted/updated for video
- Need title for Photos
- Need date created/updated, large image, totalmembers for groups

**Comment by liomj** [comment]
can't send notes, we got the message notes sent but notes is not posted
